### ISSUE TITLE
Tike specific tutorial

### ISSUE THREAD

**Issue by christinahedges** [lightkurve/lksearch#18]
I'd like to use `lksearch` on [tike](https://timeseries.science.stsci.edu/) and I believe there is a way to make it so the data does not get downloaded, and the cloud URI is returned as the "local path". That way people don't have to move files around on the cloud. 

I think we need a tutorial for this behavior, or at least some documentation so people know how to do this?

**Comment by tylerapritchard** [comment]
Yes, you are right - that behaviour definitely exists and is currently poorly documented. 

This functionality is accessible through the [DOWNLOAD_CLOUD](https://lightkurve.github.io/lksearch/apidoc.html#lksearch.Conf) configuration variable and able to be set as the default through the use of a configuration file.  

We should definitely add, at the very least, an example of how this works (and discussion of other configuraition parameters existing/point at them in the API documentation as they are fairly self explanatory) in the current (configuration) section of the tutorial.

If lksearch were to be incorporated in the TIKE TESS environment, I think a separate TIKE-focussed tutorial demonstrating the package usage in the default TESS TIKE configuration (which might include having this parameter set) would be worthwhile
